name: Build
on:
  workflow_dispatch:
    inputs:
      repoName:
        description: 'Repo name'
        required: true
        default: 'demo_project'

jobs:
  createRepoWithNameParam:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 10s to wait for the repo to be created
        run: sleep 10s 
      - name: clone new repo, change gDocPath and push
        run: |
          ssh-keygen -t ed25519 -C "my description" -N "" -f .ssh/github_rsa
          echo "Host github.com" > ~/.ssh/config
          echo "  IdentityFile ~/.ssh/github_rsa" >> ~/.ssh/config
          echo ${{ secrets.GH_TOKEN }} > secret.file &&
          gh auth login --with-token < secret.file &&
          gh auth status &&
          gh repo clone lokeshnasina/${{ github.event.inputs.repoName }} &&
          cd ${{ github.event.inputs.repoName }}
          gh repo deploy-key add -w .ssh/github_rsa.pub 
          sed -i '2s#.*#  / : ${{ github.event.inputs.gdocPath }}#g' fstab.yaml && 
          cat fstab.yaml 
          git config --global user.email "cc-adobe-devops@diva-e.com"
          git config --global user.name "Diva-e CI User"
          git remote add origin_2 git@github.com:lokeshnasina/${{ github.event.inputs.repoName }}.git  
          eval $(ssh-agent)
          ssh-add ~/.ssh/github_rsa
          git commit -am "use fstab!" 
          git push         