name: Build
on:
  workflow_dispatch:
    inputs:
      repoName:
        description: 'Repo name'
        required: true
        default: 'demo_project'

jobs:
  createRepoWithNameParam:
    runs-on: ubuntu-latest
    steps:
      - name: create new repo      
        run: |
          echo ${{ secrets.GH_TOKEN }} > secret.file &&
          gh auth login --with-token < secret.file &&
          gh auth status &&
          gh repo create ${{ github.event.inputs.repoName }} --private --template hlxsites/aem-boilerplate-commerce 
      - name: Sleep for 10s to wait for the repo to be created
        run: sleep 10s 
      - name: clone new repo, change gDocPath and push
        run: |
          echo ${{ secrets.GH_TOKEN }} > secret.file &&
          gh auth login --with-token < secret.file &&
          gh auth status &&
          gh repo clone lokeshnasina/${{ github.event.inputs.repoName }} &&
          cd ${{ github.event.inputs.repoName }}
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/github_rsa
          git remote set-url origin git@github.com:lokeshnasina/${{ github.event.inputs.repoName }}.git
          sed -i '2s#.*#  / : ${{ github.event.inputs.gdocPath }}#g' fstab.yaml && 
          cat fstab.yaml 
          git config --global user.email "lokesh.nasina@diva-e.com"
          git config --global user.name "lokeshnasina"
          git commit -am "use fstab!" 
          git push         